# espanso match file

global_vars:
  - name: first_name
    type: echo
    params:
      echo: "Ishraque"
  - name: last_name
    type: echo
    params:
      echo: "Alam"
  - name: domain
    type: echo
    params:
      echo: "ishrq.com"

matches:

# Name
  - trigger: ";name"
    replace: "{{first_name}} {{last_name}}"
    label: "Name"

# Address
  - trigger: ";ad"
    replace: "House 24 (apt.2B), Road 8, Block H (Sector 2), Aftabnagar (1212), Dhaka"
    label: "Address/home"

# Emails
  - trigger: "@@con"
    replace: "contact@{{domain}}"
    label: "Email/website/contact@ishrq.com"

  - trigger: "@@ia"
    replace: "ia@{{domain}}"
    label: "Email/private/ia@ishrq.com"

  - trigger: "@@work"
    replace: "work@{{domain}}"
    label: "Email/work/work@ishrq.com"

  - trigger: "@@gm"
    replace: "i.alam.2209@gmail.com"
    label: "Email/private/gmail"

  - trigger: "@@pm"
    replace: "ishraque-013@proton.me"
    label: "Email/private/proton"

  - trigger: "@@rf1"
    replace: "6l5k6k0c7@relay.firefox.com"
    label: "Email/relay1"

  - trigger: "@@rf2"
    replace: "sbaqcxtg6@relay.firefox.com"
    label: "Email/relay2"

  - trigger: "@@rf3"
    replace: "r4slsj8gh@relay.firefox.com"
    label: "Email/relay3"

# Date
  - trigger: ";date"
    replace: "{{mydate}}"
    label: "Date"
    vars:
      - name: mydate
        type: date
        params:
          format: "%F"

# Timestamp
  - trigger: ";ts"
    replace: "{{mydate}}"
    label: "Timestamp"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d%H%M"

# Email signature
  - trigger: ";sig"
    replace: "{{output}}"
    label: "Email signature"
    vars:
      - name: output
        type: choice
        params:
          values:
            - "Regards,\n{{first_name}} {{last_name}}"
            - "Sincerely,\n{{first_name}} {{last_name}}"
            - "Thank you,\n{{first_name}} {{last_name}}"

# Text

  - trigger: ";em"
    replace: "—"
    label: "Em dash"

  - trigger: ";el"
    replace: "…"
    label: "Ellipsis"

  - trigger: ";tdc"
    replace: "thedhakacrawler.com"
    label: "TDC domain"









# ------------
